luac -o compiled\angles.luc angles.lua
luac -o compiled\animation.luc animation.lua
luac -o compiled\base64.luc base64.lua
luac -o compiled\cl_init.luc cl_init.lua
luac -o compiled\commands.luc commands.lua
luac -o compiled\complex.luc complex.lua
luac -o compiled\custom.luc custom.lua
luac -o compiled\custom_ents.luc custom_ents.lua
luac -o compiled\custom_games.luc custom_games.lua
luac -o compiled\custom_weapons.luc custom_weapons.lua
luac -o compiled\downloader.luc downloader.lua
luac -o compiled\downloader2.luc downloader2.lua
luac -o compiled\entities.luc entities.lua
luac -o compiled\enum.luc enum.lua
luac -o compiled\extensions\init.luc extensions\init.lua
luac -o compiled\extensions\string.luc extensions\string.lua
luac -o compiled\extensions\table.luc extensions\table.lua
luac -o compiled\file.luc file.lua
luac -o compiled\fonts.luc fonts.lua
luac -o compiled\functiondump.luc functiondump.lua
luac -o compiled\hooks.luc hooks.lua
luac -o compiled\init.luc init.lua
luac -o compiled\input.luc input.lua
luac -o compiled\linkedlist.luc linkedlist.lua
luac -o compiled\matrix.luc matrix.lua
luac -o compiled\messageproto.luc messageproto.lua
luac -o compiled\model.luc model.lua
luac -o compiled\netvars.luc netvars.lua
luac -o compiled\packs.luc packs.lua
luac -o compiled\particletools.luc particletools.lua
luac -o compiled\player.luc player.lua
luac -o compiled\poly.luc poly.lua
luac -o compiled\persistance.luc persistance.lua
luac -o compiled\qml.luc qml.lua
luac -o compiled\scriptmanager.luc scriptmanager.lua
luac -o compiled\sequence.luc sequence.lua
luac -o compiled\shader.luc shader.lua
luac -o compiled\shared.luc shared.lua
luac -o compiled\sound.luc sound.lua
luac -o compiled\spring.luc spring.lua
luac -o compiled\sprite.luc sprite.lua
luac -o compiled\test_complex.luc test_complex.lua
luac -o compiled\test_matrix.luc test_matrix.lua
luac -o compiled\timer.luc timer.lua
luac -o compiled\tools.luc tools.lua
luac -o compiled\treeparser.luc treeparser.lua
luac -o compiled\vector.luc vector.lua
luac -o compiled\view.luc view.lua